---
booktitle: Proceedings of Fourth European Workshop on Algorithmic Fairness
shortname: EWAF
sections:
- name: Preface
  title: Preface
- name: Full Papers
  title: Full Papers
- name: Extended Abstracts
  title: Extended Abstracts
volume: '294'
year: '2025'
start: &1 2025-06-30
end: 2025-07-02
published: 2025-07-09
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: EWAF-2025
month: 0
cycles: false
bibtex_editor: Weerts, Hilde and Pechenizkiy, Mykola and Allhutter, Doris and Corr\^ea,
  Ana Maria and Grote, Thomas and Liem, Cynthia
editor:
- given: Hilde
  family: Weerts
- given: Mykola
  family: Pechenizkiy
- given: Doris
  family: Allhutter
- given: Ana Maria
  family: Corrêa
- given: Thomas
  family: Grote
- given: Cynthia
  family: Liem
title: Proceedings of Machine Learning Research
description: |
  Proceedings of Fourth European Workshop on Algorithmic Fairness
    Held in Eindhoven University of Technology, Eindhoven, The Netherlands on 30 June to 02 July 2025

  Published as Volume 294 by the Proceedings of Machine Learning Research on 09 July 2025.

  Volume Edited by:
    Hilde Weerts
    Mykola Pechenizkiy
    Doris Allhutter
    Ana Maria Corrêa
    Thomas Grote
    Cynthia Liem

  Series Editors:
    Neil D. Lawrence
date_str: 30 Jun--02 Jul
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v294"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v294
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v294
email: ''
conference:
  name: European Workshop on Algorithmic Fairness
  url: https://2025.ewaf.org/
  location: Eindhoven University of Technology, Eindhoven, The Netherlands
  dates:
  - *1
  - 2025-07-01
  - 2025-07-02
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: ewaf25_clean.bib
# Site settings
# Original source:  ewaf25_clean.bib
